### ISSUE TITLE
BK-tree

### ISSUE THREAD

**Issue by 6gales** [6gales/CompTech#5]
Деревья Баркхарда-Келлера - метрические деревьями, которые можно строить, если метрика отвечает неравенству треугольника. Метрики Левенштейна и Дамерау-Левенштейна, в частности, этому неравенству удовлетворяют.

**Comment by AlexKireev15** [comment]
Закрывать issue самому себе без проверки это такое :D

**Comment by 6gales** [comment]
Соре, не знал, проверишь?

чт, 31 янв. 2019 г., 14:40 Alex Kireev notifications@github.com:

**Comment by AlexKireev15** [comment]
Ну, нужно тестер дождаться

**Comment by 6gales** [comment]
Ну ладно, а обратно открыть нельзя? Я ещё не понял, почему он не
заасигнился ко мне

чт, 31 янв. 2019 г., 14:57 Alex Kireev notifications@github.com:

**Comment by AlexKireev15** [comment]
Протестить код

**Comment by AlexKireev15** [comment]
пофиксил

**Comment by 6gales** [comment]
Спасибо
